baseurl: ""
url: "https://shir-bot.ze-kal.top"
language: "he"

title: "שיר-בוט | חיפוש והורדת מוזיקה יהודית וחסידית | מאגר עדכני"

description: >-
  שיר-בוט: חיפוש מתקדם והורדה קלה של מוזיקה יהודית וחסידית.
  מאגר ענק ועדכני של שירים, סינגלים, אלבומים ואמנים.
  מצאו את השיר הבא שלכם!

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - ./_plugins/artist_page_generator.rb

seo:
  title: "שיר-בוט - מאגר מוזיקה יהודית וחסידית"
  description: "חיפוש, גילוי והורדה של שירים, אלבומים ואמנים מהמוזיקה היהודית והחסידית. המאגר הגדול והמתעדכן של שיר-בוט."
  url: "https://shir-bot.ze-kal.top"
  image: "/assets/images/logo.png"

data_dir: _data

safe: false