# docs/_config.yml

# ה-baseurl של האתר הישן ב-GitHub Pages
# חשוב להגדרה נכונה של בנייה מקומית ושל ה-Action
baseurl: "/shir-bot" 
url: "https://nhlocal.github.io" # ה-url הישן של GitHub Pages

language: "he"
title: "שיר-בוט | האתר עבר כתובת"
description: "האתר של שיר-בוט עבר לכתובת חדשה. אנו מפנים אותך כעת."

# רשימת פלאגינים מצומצמת - רק אלה שיוצרים את הדפים
plugins:
  - ./_plugins/artist_page_generator.rb
  - ./_plugins/monthly_archive_generator.rb

safe: false

# הגדרת ברירת המחדל להפניה - זה נשאר כמו שהיה
defaults:
  -
    scope:
      path: "" 
    values:
      layout: "redirect"