name: Run Python Script

on:
  # workflow_dispatch:  # Allows manual triggering
  push:


jobs:
  run_script:
    runs-on: ubuntu-latest

    env:
      SERVICE_ACCOUNT_JSON: ${{ secrets.ACCESS_KEYS_JSON }} # Using the secret

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

    - name: Set up environment variables
      run: echo "$SERVICE_ACCOUNT_JSON" > service-account-file.json

    - name: Run Python script
      run: python creat-data/index_for_drive2.py
      
      env:
        ACTIONS_STEP_DEBUG: true

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: NHLOCAL
          author_email: NH.LOCAL11@GMAIL.COM
          message: 'Your commit message'
          add: 'output.csv'


      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        


