name: Sync Drive Shortcuts

on:
  push:
    branches:
      - "new-singles" # שנה ל-master אם זה הענף הראשי שלך
    paths:
      # Trigger only when the Python script itself changes
      - 'creat-data/drive_shortcut_creator.py'

jobs:
  run-script:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies directly
      # התקנת התלויות ישירות דרך pip במקום מקובץ requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 certifi

    - name: Create Google Credentials Files from Secrets
      run: |
        echo "${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}" > client_secret_auth.json
        echo "${{ secrets.GOOGLE_TOKEN_JSON }}" > token.json
      env:
        GOOGLE_CLIENT_SECRET_JSON: ${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}
        GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}

    - name: Run the Python script
      run: python drive_shortcut_creator.py 

    - name: Clean up credential files 
      if: always() 
      run: |
        rm -f client_secret_auth.json
        rm -f token.json