name: Sync Drive Shortcuts

on:
  push:
    branches:
      - "new-singles" # שנה ל-master אם זה הענף הראשי שלך
    paths:
      # Trigger only when the Python script itself changes
      - 'drive_shortcut_creator.py' 
  # מאפשר הרצה ידנית דרך ממשק ה-Actions ב-GitHub (אופציונלי)
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 

    - name: Install dependencies directly
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 certifi

    # --- שלב יצירת הקבצים הוסר ---

    - name: Run the Python script with Secrets as Env Vars
      # הרצת הסקריפט כשהסודות זמינים כמשתני סביבה
      run: python drive_shortcut_creator.py 
      env:
        # חשוב: העברת הסודות למשתני סביבה שהסקריפט יקרא
        GOOGLE_CLIENT_SECRET_JSON: ${{ secrets.GOOGLE_CLIENT_SECRET_JSON }}
        GOOGLE_TOKEN_JSON: ${{ secrets.GOOGLE_TOKEN_JSON }}