name: Download CSV from Google Drive

on:
  push:
    branches:
      - main  # Change this to your preferred branch

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Use the Python version you prefer

    - name: Install dependencies
      run: pip install gdown

    - name: Download CSV from Google Drive
      run: |
        # Specify the Google Drive file ID for your CSV
        file_id="1X1hSFrgrar5T8kE8pHlDbwXHoAEeRcPs"

        # Specify the output file name
        output_file="output.csv"

        # Download the file
        gdown "https://drive.google.com/uc?id=$file_id" -O $output_file
      env:
        file_id: ${{ secrets.GOOGLE_DRIVE_FILE_ID }}

    - name: Commit and push changes
      run: |
        git config user.name "NHLOCAL"
        git config user.email "nh.local11@gmail.com"
        git add $output_file
        git commit -m "Add downloaded CSV"
        git push
