name: Download File from Google Drive

on:
  push:
    branches:
      - main

jobs:
  download-file:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download File
      run: |
        curl -L "https://docs.google.com/uc?export=download&id=1X1hSFrgrar5T8kE8pHlDbwXHoAEeRcPs" > file.csv

    - name: Commit and Push
      run: |
        git config --global user.email "nh.local11@gmail.com"
        git config --global user.name "NHLOCAL"
        git add file.csv
        git commit -m "Download file from Google Drive"
        git push
