name: Download File from Google Drive

on:
  push:
    branches:
      - main

jobs:
  download-file:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download File
      run: |
        Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=YOUR_FILE_ID" -OutFile "file.csv"
      env:
        YOUR_FILE_ID: 1TMiSV0sBCPn29KDs4rkdZMxRpvWG2TvP

    - name: Commit and Push
      run: |
        git config --global user.email "nh.local11@gmail.com"
        git config --global user.name "NHLOCAL"
        git add file.csv
        git commit -m "Download file from Google Drive"
        git push
