name: Upload new singles to Drive

on:
  push:
    branches:
      - main
      - new-singles
    paths:
      # טריגר אם הסקריפטים, ה-workflow או התלויות משתנים
      - 'drive_data/process_drive_folder.py'
      - 'drive_data/csv_to_yaml_converter.py'
      - '.github/workflows/process_drive.yml'
      - 'requirements.txt'
  workflow_dispatch:
  schedule:
    # יומי ב-4:00 UTC
    - cron: '45 23 * * *'

permissions:
  contents: write # נדרש לביצוע commit חזרה לריפו

jobs:
  process-drive-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # או גרסת פייתון אחרת

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # הנחה ש-requirements.txt נמצא בשורש הריפו
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Authenticate Google Drive (Target Account)
        env:
          GDRIVE_TOKEN_JSON_CONTENT: ${{ secrets.GDRIVE_TOKEN_JSON }}
        run: |
          if [ -z "$GDRIVE_TOKEN_JSON_CONTENT" ]; then
            echo "::error::GDRIVE_TOKEN_JSON secret is not set or empty. Authentication cannot proceed."
            exit 1
          else
            echo "Google Drive secret found. Proceeding..."
          fi

      - name: Run Drive Processing Script
        env:
          GDRIVE_TOKEN_JSON_CONTENT: ${{ secrets.GDRIVE_TOKEN_JSON }}
        run: python drive_data/process_drive_folder.py

      # --- שלב מעודכן: הרצת סקריפט ההמרה הנפרד ---
      - name: Convert new-songs.csv to YAML using script
        run: |
          python drive_data/csv_to_yaml_converter.py \
            --csv-input drive_data/new-songs.csv \
            --yaml-output docs/_data/new_songs.yml

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # שלב בדיקת השינויים נשאר זהה - הוא כבר בודק את הקבצים הנכונים
      - name: Check for changes in state, csv, or yaml file
        id: check_changes
        run: |
          git add drive_data/drive_state.json drive_data/new-songs.csv docs/_data/new_songs.yml
          if git diff --staged --quiet; then
            echo "No changes detected in state file, CSV, or YAML."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in state file, CSV, or YAML."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      # שלב ה-Commit וה-Push נשאר זהה
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git commit -m "Update Drive state, CSV, and YAML from processing [skip ci]"
          retry_count=0
          max_retries=3
          until git pull --rebase && git push || [ $retry_count -eq $max_retries ]; do
            retry_count=$((retry_count+1))
            echo "Push failed or conflict detected. Retrying ($retry_count/$max_retries) after git pull --rebase in 15 seconds..."
            sleep 15
          done
          if [ $retry_count -eq $max_retries ]; then
            echo "::error::Failed to push changes after multiple retries. Please check for conflicts manually."
            exit 1
          else
            echo "Changes committed and pushed successfully."
          fi
