name: Test Cloudflare Deploy Hook

# מאפשר הפעלה ידנית בלבד דרך ממשק ה-Actions של GitHub
on:
  workflow_dispatch:

jobs:
  test-deploy-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Test Deploy Request to Cloudflare
        run: |
          echo "Sending a test deploy request to Cloudflare..."
          curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}"
          echo "Request sent! Please go to your Cloudflare Pages project to see if a new build has started."